# Generated by Django 6.0.4 on 2026-04-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('puerta_acceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacion.puertaacceso')),
            ],
        ),
        migrations.CreateModel(
            name='ComandoRemoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=50)),
                ('parametro', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
            ],
        ),
    ]
